/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
package com.telstra.api.models;

import java.util.*;

public class AuthenticationResponseBuilder {
    //the instance to build
    private AuthenticationResponse authenticationResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AuthenticationResponseBuilder() {
        authenticationResponse = new AuthenticationResponse();
    }

    public AuthenticationResponseBuilder accessToken(String accessToken) {
        authenticationResponse.setAccessToken(accessToken);
        return this;
    }

    public AuthenticationResponseBuilder expiresIn(String expiresIn) {
        authenticationResponse.setExpiresIn(expiresIn);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AuthenticationResponse build() {
        return authenticationResponse;
    }
}