/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
package com.telstra.api.models;

import java.util.*;

public class GetAuthenticationInputBuilder {
    //the instance to build
    private GetAuthenticationInput getAuthenticationInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetAuthenticationInputBuilder() {
        getAuthenticationInput = new GetAuthenticationInput();
    }

    public GetAuthenticationInputBuilder clientId(String clientId) {
        getAuthenticationInput.setClientId(clientId);
        return this;
    }

    public GetAuthenticationInputBuilder clientSecret(String clientSecret) {
        getAuthenticationInput.setClientSecret(clientSecret);
        return this;
    }

    public GetAuthenticationInputBuilder grantType(String grantType) {
        getAuthenticationInput.setGrantType(grantType);
        return this;
    }

    public GetAuthenticationInputBuilder scope(String scope) {
        getAuthenticationInput.setScope(scope);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetAuthenticationInput build() {
        return getAuthenticationInput;
    }
}