/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
package com.telstra.api.models;

import java.util.*;

public class MessageResponseBuilder {
    //the instance to build
    private MessageResponse messageResponse;

    /**
     * Default constructor to initialize the instance
     */
    public MessageResponseBuilder() {
        messageResponse = new MessageResponse();
    }

    public MessageResponseBuilder acknowledgedTimestamp(String acknowledgedTimestamp) {
        messageResponse.setAcknowledgedTimestamp(acknowledgedTimestamp);
        return this;
    }

    public MessageResponseBuilder content(String content) {
        messageResponse.setContent(content);
        return this;
    }

    public MessageResponseBuilder from(String from) {
        messageResponse.setFrom(from);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MessageResponse build() {
        return messageResponse;
    }
}